'use client';

import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'pt-BR' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  'pt-BR': {
    'locale': 'pt-BR',
    'currency': 'R$',
    'dashboard.title': 'Dashboard Principal',
    'dashboard.subtitle': 'Status em tempo real de todas as zonas de implantação ativas.',
    'dashboard.guardsOnDuty': 'Vigilantes em Serviço',
    'dashboard.activePostSites': 'Postos Ativos',
    'dashboard.openIncidentReports': 'Relatórios de Incidentes Abertos',
    'dashboard.activeAlarms': 'Alarmes Ativos',
    'dashboard.globalMonitoring': 'Monitoramento Global',
    'dashboard.allZones': 'Todas as Zonas',
    'dashboard.live': 'Ao Vivo',
    'dashboard.activePatrol': 'Patrulha Ativa',
    'dashboard.stationary': 'Estacionário',
    'dashboard.alarmTriggered': 'Alarme Disparado',
    'dashboard.patrolCompletion': 'Conclusão de Patrulhas',
    'dashboard.averageRate': 'Taxa Média',
    'dashboard.bestPerformance': 'Melhor desempenho este mês no Site-A',
    'dashboard.recentAlerts': 'Alertas Recentes',
    'dashboard.viewAllActivity': 'Ver Toda Atividade',
    'dashboard.time': 'Hora',
    'dashboard.guard': 'Vigilante',
    'dashboard.location': 'Local',
    'dashboard.alertType': 'Tipo de Alerta',
    'dashboard.status': 'Status',
    'dashboard.actions': 'Ações',
    'sidebar.dashboard': 'Dashboard',
    'sidebar.clients': 'Minhas Vagas',
    'sidebar.availableJobs': 'Vagas Disponíveis',
    'sidebar.myProfile': 'Meu Perfil',
    'sidebar.locations': 'Locais de Posto',
    'sidebar.guards': 'Vigilantes',
    'sidebar.users': 'Usuários',
    'sidebar.reports': 'Relatórios',
    'sidebar.schedules': 'Escalas',
    'sidebar.dispatch': 'Despacho',
    'sidebar.billing': 'Faturamento',
    'sidebar.logout': 'Sair do Sistema',
    'sidebar.adminControl': 'Controle Admin',
    'header.search': 'Buscar...',
    'header.notifications': 'Notificações',
    'header.settings': 'Configurações',
    'clients.title': 'Portal do Cliente',
    'clients.subtitle': 'Publique vagas e gerencie demandas de segurança.',
    'clients.newJob': 'Nova Requisição de Vaga',
    'clients.noJobs': 'Nenhuma vaga postada',
    'clients.noJobsDesc': 'Comece publicando uma nova vaga para seus postos.',
    'clients.statusOpen': 'Aberta',
    'clients.statusClosed': 'Fechada',
    'clients.noLocation': 'Local não informado',
    'clients.guards': 'Vigilante(s)',
    'clients.hydration': 'Hidratação',
    'clients.closeJob': 'Fechar Vaga',
    'clients.reopenJob': 'Reabrir Vaga',
    'clients.modalTitle': 'Publicar Nova Vaga de Segurança',
    'clients.deleteConfirm': 'Excluir esta vaga permanentemente?',
    'sites.title': 'Gestão de Postos',
    'sites.newSite': 'Novo Posto',
    'sites.search': 'Pesquisar por nome, endereço ou cliente...',
    'sites.status': 'Status',
    'sites.all': 'Todos',
    'sites.colName': 'Nome do Posto',
    'sites.colAddress': 'Endereço',
    'sites.colGuards': 'Vigilantes',
    'sites.colClient': 'Cliente',
    'sites.colStatus': 'Status',
    'sites.colActions': 'Ações',
    'sites.noGuards': 'Sem vigilantes',
    'sites.guardsLabel': 'vigilantes',
    'sites.statusActive': 'Ativo',
    'sites.statusMaintenance': 'Manutenção',
    'sites.showing': 'Mostrando',
    'sites.results': 'resultados',
    'sites.prev': 'Anterior',
    'sites.next': 'Próximo',
    'sites.activeSites': 'Postos Ativos',
    'sites.pendingSites': 'Pendentes',
    'sites.totalCoverage': 'Cobertura Total',
    'sites.editSite': 'Editar Posto',
    'sites.addSite': 'Adicionar Novo Posto',
    'sites.deleteConfirm': 'Tem certeza que deseja excluir este posto?',
    'guards.title': 'Gestão de Guardas',
    'guards.export': 'Exportar',
    'guards.selfRegister': 'Cadastro do Segurança',
    'guards.newGuard': 'Adicionar Novo Guarda',
    'guards.filterStatus': 'Todos os Status',
    'guards.statusActive': 'Ativo',
    'guards.statusBreak': 'Em Intervalo',
    'guards.statusOffline': 'Offline',
    'guards.filterSites': 'Todos os Postos',
    'guards.filterRank': 'Patente/Rank',
    'guards.colName': 'Foto/Nome',
    'guards.colContact': 'Contato',
    'guards.colSite': 'Posto Designado',
    'guards.colStatus': 'Status',
    'guards.colPerformance': 'Desempenho',
    'guards.colActions': 'Ações',
    'guards.showing': 'Mostrando',
    'guards.results': 'guardas registrados',
    'guards.prev': 'Anterior',
    'guards.next': 'Próximo',
    'guards.editGuard': 'Editar Guarda',
    'guards.addGuard': 'Adicionar Novo Guarda',
    'guards.deleteConfirm': 'Tem certeza que deseja excluir este guarda?',
    'dispatch.title': 'Central de Despacho',
    'dispatch.subtitle': 'Comunicação em Tempo Real',
    'dispatch.description': 'O módulo de despacho por rádio e monitoramento de voz está sendo inicializado.',
    'dispatch.systemOnline': 'Sistema Online',
    'schedule.title': 'Escala de Guardas',
    'schedule.addShift': 'Adicionar Turno',
    'schedule.day': 'Dia',
    'schedule.week': 'Semana',
    'schedule.month': 'Mês',
    'schedule.filters': 'Filtros',
    'schedule.exportPdf': 'Exportar PDF',
    'schedule.guards': 'Guardas',
    'schedule.openJobs': 'Vagas abertas',
    'schedule.available': 'Disponível',
    'schedule.filterTitle': 'Filtros da Escala',
    'schedule.filterByStatus': 'Filtrar por Status',
    'schedule.filterOpen': 'Vagas Abertas',
    'schedule.filterClosed': 'Vagas Fechadas',
    'schedule.filterConfirmed': 'Confirmadas',
    'schedule.filterPending': 'Pendentes',
    'schedule.resetFilters': 'Resetar Filtros',
    'schedule.totalShifts': 'Total de Turnos',
    'schedule.assigned': 'Atribuídos',
    'schedule.pending': 'Pendentes',
    'schedule.lastSync': 'Última sincronização: Hoje, 14:22',
    'billing.title': 'Faturamento e Cobrança',
    'billing.totalBilled': 'Total Faturado (Mês)',
    'billing.toReceive': 'A Receber',
    'billing.overdue': 'Faturas Vencidas',
    'billing.management': 'Gestão Financeira',
    'billing.description': 'Visualize faturas, contratos e pagamentos de todos os clientes.',
    'reports.title': 'Relatórios de Atividade',
    'reports.generateNew': 'Gerar Novo Relatório',
    'reports.incidentsToday': 'Incidentes Hoje',
    'reports.vsYesterday': '+2 vs ontem',
    'reports.patrolsCompleted': 'Patrulhas Concluídas',
    'reports.successRate': '98% de sucesso',
    'reports.pendingReports': 'Relatórios Pendentes',
    'reports.requiresAttention': 'Requer atenção',
    'reports.search': 'Buscar relatórios...',
    'reports.filters': 'Filtros',
    'reports.exportCsv': 'Exportar CSV',
    'reports.noRecent': 'Nenhum relatório recente',
    'reports.allProcessed': 'Todos os relatórios de hoje foram processados.',
    'users.title': 'Gestão de Usuários',
    'users.subtitle': 'Gerencie as contas que têm acesso ao sistema.',
    'users.colUser': 'Usuário',
    'users.colEmail': 'Email',
    'users.colRole': 'Função',
    'users.colActions': 'Ações',
    'users.deleteUser': 'Excluir Usuário',
    'users.deleteConfirm': 'Tem certeza que deseja excluir este usuário?',
  },
  'en': {
    'locale': 'en-US',
    'currency': '$',
    'dashboard.title': 'Main Dashboard',
    'dashboard.subtitle': 'Real-time status of all active deployment zones.',
    'dashboard.guardsOnDuty': 'Guards on Duty',
    'dashboard.activePostSites': 'Active Post Sites',
    'dashboard.openIncidentReports': 'Open Incident Reports',
    'dashboard.activeAlarms': 'Active Alarms',
    'dashboard.globalMonitoring': 'Global Monitoring',
    'dashboard.allZones': 'All Zones',
    'dashboard.live': 'Live',
    'dashboard.activePatrol': 'Active Patrol',
    'dashboard.stationary': 'Stationary',
    'dashboard.alarmTriggered': 'Alarm Triggered',
    'dashboard.patrolCompletion': 'Patrol Completion',
    'dashboard.averageRate': 'Average Rate',
    'dashboard.bestPerformance': 'Best performance this month at Site-A',
    'dashboard.recentAlerts': 'Recent Alerts',
    'dashboard.viewAllActivity': 'View All Activity',
    'dashboard.time': 'Time',
    'dashboard.guard': 'Guard',
    'dashboard.location': 'Location',
    'dashboard.alertType': 'Alert Type',
    'dashboard.status': 'Status',
    'dashboard.actions': 'Actions',
    'sidebar.dashboard': 'Dashboard',
    'sidebar.clients': 'My Jobs',
    'sidebar.availableJobs': 'Available Jobs',
    'sidebar.myProfile': 'My Profile',
    'sidebar.locations': 'Post Locations',
    'sidebar.guards': 'Guards',
    'sidebar.users': 'Users',
    'sidebar.reports': 'Reports',
    'sidebar.schedules': 'Schedules',
    'sidebar.dispatch': 'Dispatch',
    'sidebar.billing': 'Billing',
    'sidebar.logout': 'Logout',
    'sidebar.adminControl': 'Admin Control',
    'header.search': 'Search...',
    'header.notifications': 'Notifications',
    'header.settings': 'Settings',
    'clients.title': 'Client Portal',
    'clients.subtitle': 'Post jobs and manage security demands.',
    'clients.newJob': 'New Job Request',
    'clients.noJobs': 'No jobs posted',
    'clients.noJobsDesc': 'Start by posting a new job for your sites.',
    'clients.statusOpen': 'Open',
    'clients.statusClosed': 'Closed',
    'clients.noLocation': 'Location not provided',
    'clients.guards': 'Guard(s)',
    'clients.hydration': 'Hydration',
    'clients.closeJob': 'Close Job',
    'clients.reopenJob': 'Reopen Job',
    'clients.modalTitle': 'Post New Security Job',
    'clients.deleteConfirm': 'Permanently delete this job?',
    'sites.title': 'Site Management',
    'sites.newSite': 'New Site',
    'sites.search': 'Search by name, address or client...',
    'sites.status': 'Status',
    'sites.all': 'All',
    'sites.colName': 'Site Name',
    'sites.colAddress': 'Address',
    'sites.colGuards': 'Guards',
    'sites.colClient': 'Client',
    'sites.colStatus': 'Status',
    'sites.colActions': 'Actions',
    'sites.noGuards': 'No guards',
    'sites.guardsLabel': 'guards',
    'sites.statusActive': 'Active',
    'sites.statusMaintenance': 'Maintenance',
    'sites.showing': 'Showing',
    'sites.results': 'results',
    'sites.prev': 'Previous',
    'sites.next': 'Next',
    'sites.activeSites': 'Active Sites',
    'sites.pendingSites': 'Pending',
    'sites.totalCoverage': 'Total Coverage',
    'sites.editSite': 'Edit Site',
    'sites.addSite': 'Add New Site',
    'sites.deleteConfirm': 'Are you sure you want to delete this site?',
    'guards.title': 'Guard Management',
    'guards.export': 'Export',
    'guards.selfRegister': 'Guard Self-Registration',
    'guards.newGuard': 'Add New Guard',
    'guards.filterStatus': 'All Statuses',
    'guards.statusActive': 'Active',
    'guards.statusBreak': 'On Break',
    'guards.statusOffline': 'Offline',
    'guards.filterSites': 'All Sites',
    'guards.filterRank': 'Rank/Tier',
    'guards.colName': 'Photo/Name',
    'guards.colContact': 'Contact',
    'guards.colSite': 'Assigned Site',
    'guards.colStatus': 'Status',
    'guards.colPerformance': 'Performance',
    'guards.colActions': 'Actions',
    'guards.showing': 'Showing',
    'guards.results': 'registered guards',
    'guards.prev': 'Previous',
    'guards.next': 'Next',
    'guards.editGuard': 'Edit Guard',
    'guards.addGuard': 'Add New Guard',
    'guards.deleteConfirm': 'Are you sure you want to delete this guard?',
    'dispatch.title': 'Dispatch Center',
    'dispatch.subtitle': 'Real-Time Communication',
    'dispatch.description': 'The radio dispatch and voice monitoring module is initializing.',
    'dispatch.systemOnline': 'System Online',
    'schedule.title': 'Guard Schedule',
    'schedule.addShift': 'Add Shift',
    'schedule.day': 'Day',
    'schedule.week': 'Week',
    'schedule.month': 'Month',
    'schedule.filters': 'Filters',
    'schedule.exportPdf': 'Export PDF',
    'schedule.guards': 'Guards',
    'schedule.openJobs': 'Open Jobs',
    'schedule.available': 'Available',
    'schedule.filterTitle': 'Schedule Filters',
    'schedule.filterByStatus': 'Filter by Status',
    'schedule.filterOpen': 'Open Jobs',
    'schedule.filterClosed': 'Closed Jobs',
    'schedule.filterConfirmed': 'Confirmed',
    'schedule.filterPending': 'Pending',
    'schedule.resetFilters': 'Reset Filters',
    'schedule.totalShifts': 'Total Shifts',
    'schedule.assigned': 'Assigned',
    'schedule.pending': 'Pending',
    'schedule.lastSync': 'Last sync: Today, 14:22',
    'billing.title': 'Billing & Invoicing',
    'billing.totalBilled': 'Total Billed (Month)',
    'billing.toReceive': 'To Receive',
    'billing.overdue': 'Overdue Invoices',
    'billing.management': 'Financial Management',
    'billing.description': 'View invoices, contracts, and payments for all clients.',
    'reports.title': 'Activity Reports',
    'reports.generateNew': 'Generate New Report',
    'reports.incidentsToday': 'Incidents Today',
    'reports.vsYesterday': '+2 vs yesterday',
    'reports.patrolsCompleted': 'Patrols Completed',
    'reports.successRate': '98% success rate',
    'reports.pendingReports': 'Pending Reports',
    'reports.requiresAttention': 'Requires attention',
    'reports.search': 'Search reports...',
    'reports.filters': 'Filters',
    'reports.exportCsv': 'Export CSV',
    'reports.noRecent': 'No recent reports',
    'reports.allProcessed': 'All reports for today have been processed.',
    'users.title': 'User Management',
    'users.subtitle': 'Manage accounts that have access to the system.',
    'users.colUser': 'User',
    'users.colEmail': 'Email',
    'users.colRole': 'Role',
    'users.colActions': 'Actions',
    'users.deleteUser': 'Delete User',
    'users.deleteConfirm': 'Are you sure you want to delete this user?',
  }
};

const LanguageContext = createContext<LanguageContextType>({
  language: 'pt-BR',
  setLanguage: () => {},
  t: (key: string) => key,
});

export const useLanguage = () => useContext(LanguageContext);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>('pt-BR');

  useEffect(() => {
    const savedLang = localStorage.getItem('app-language') as Language;
    if (savedLang && (savedLang === 'pt-BR' || savedLang === 'en')) {
      setLanguage(savedLang);
    }
  }, []);

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang);
    localStorage.setItem('app-language', lang);
  };

  const t = (key: string): string => {
    // @ts-ignore
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}
